In [1]:
import numpy as np
import pandas as pd


from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('/Users/ankushkumar/AI-Ml/Ai-Ml-Lab/phone_churn.csv')

df.head()

,customer_id,age,plan_type,network_type,monthly_bill,data_used_mb,call_drops_per_week,complaints_last_3m,months_with_provider,churned
0,CUST2001,24,Postpaid,4G,624,9960.0,3,0,2.0,1
1,CUST2002,24,Prepaid,4G,409,NaN,1,0,6.0,1
2,CUST2003,56,Prepaid,5G,662,15700.0,2,0,11.0,1
3,CUST2004,41,Prepaid,4G,516,15390.0,5,0,3.0,1
4,CUST2005,46,Postpaid,5G,484,42000.0,1,1,13.0,0

In [3]:
df.shape

(450, 10)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           450 non-null    str
 1   age                   450 non-null    int64
 2   plan_type             450 non-null    str
 3   network_type          450 non-null    str
 4   monthly_bill          450 non-null    int64
 5   data_used_mb          436 non-null    float64
 6   call_drops_per_week   450 non-null    int64
 7   complaints_last_3m    450 non-null    int64
 8   months_with_provider  440 non-null    float64
 9   churned               450 non-null    int64
dtypes: float64(2), int64(5), str(3)
memory usage: 42.9 KB

In [5]:
df.describe()

,age,monthly_bill,data_used_mb,call_drops_per_week,complaints_last_3m,months_with_provider,churned
count,450.000000,450.000000,436.000000,450.000000,450.000000,440.000000,450.000000
mean,41.128889,542.984444,17835.550459,3.008889,0.842222,28.702273,0.528889
std,14.189501,242.101586,13466.680872,1.773327,0.900133,23.963431,0.499720
min,18.000000,99.000000,1870.000000,0.000000,0.000000,1.000000,0.000000
25%,28.000000,369.000000,9037.500000,2.000000,0.000000,10.000000,0.000000
50%,41.000000,529.000000,14035.000000,3.000000,1.000000,23.000000,1.000000
75%,53.750000,687.250000,21840.000000,4.000000,1.000000,40.000000,1.000000
max,65.000000,1279.000000,80000.000000,9.000000,4.000000,96.000000,1.000000

In [ ]:
# Q2.2 Drop customer_id, and fill the missing values in data_used_mb and months_with_provider with the median of each column

x = df.drop(columns=)
y = df['customer_id']
print(x)
print(y)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices