In [1]:
import numpy as np

In [2]:
import pandas as pd

In [10]:
tips = pd.read_csv('tips.csv')
s = pd.read_csv('bookings.csv')
t = pd.read_csv('mpg.csv')

In [4]:
s.head()

   booking_id        customer  day    time  party_size
0         101     ravi sharma  Sat  Dinner         4.0
1         102      PRIYA IYER  Sat  Dinner         2.0
2         103    Ravi Sharma   Sun   Lunch         NaN
3         104      amit kumar  Sun  Dinner         6.0
4         105     priya  iyer  Fri  Dinner         NaN

In [5]:
t.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [8]:
s.groupby("day")

In [11]:
tips.head(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [12]:
tips.groupby("day").agg(
    bill_count = ("total_bill", "size"),
    average_bill = ("total_bill", "mean"),
    avg_tip = ("tip", "mean"),
)

      bill_count  average_bill   avg_tip
day
Fri           19     17.151579  2.734737
Sat           87     20.441379  2.993103
Sun           76     21.410000  3.255132
Thur          62     17.682742  2.771452

In [ ]:
tips.groupby("day").agg(
    bill_count = ("total_bill", "size"),
    average_bill = ("total_bill", "mean"),
    avg_party_size = ("size", "mean")
).round(2)
# summary

In [27]:
# summary = pd.

In [28]:
# summary[summary("day") == "sun"]

In [29]:
# summary.columns

In [30]:
# flat = summary.reset_index()
# print(flat.columns)

In [36]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [37]:
# your turn 
tips.groupby("day")["tip"].idxmax()

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64

In [38]:
print(tips.groupby("day")["tip"].max())

day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64